// Generated by tools/true60/gen_sites.py from tools/true60/sites_*.txt. Do not edit.
#include "runtime.h"
#include "true60.h"

// camera: Run: m148 += (forwardCheckAngle() - m148) * FwdCushion
extern "C" void site_024FE89C(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: Run: bank -= bank * 0.05
extern "C" void site_024FEB00(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x38
extern "C" void site_02502CCC(Cpu* c) { true60::ratio_begin(c, 13); }
extern "C" void site_02502CD0(Cpu* c) { true60::ratio_end(c, 13); }
// camera: followCamera state +0x34
extern "C" void site_02502E44(Cpu* c) { true60::ratio_begin(c, 8); }
extern "C" void site_02502E48(Cpu* c) { true60::ratio_end(c, 8); }
// camera: followCamera state +0x34
extern "C" void site_02502E8C(Cpu* c) { true60::ratio_begin(c, 8); }
extern "C" void site_02502E90(Cpu* c) { true60::ratio_end(c, 8); }
// camera: followCamera state +0x34
extern "C" void site_02502ECC(Cpu* c) { true60::ratio_begin(c, 8); }
extern "C" void site_02502ED0(Cpu* c) { true60::ratio_end(c, 8); }
// camera: followCamera: m3C0 += (player - m3C0) * r
extern "C" void site_0250329C(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera: mCenter += (m3C0 - mCenter) * dVar23
extern "C" void site_025032CC(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x3C
extern "C" void site_025034AC(Cpu* c) { true60::ratio_begin(c, 31); }
extern "C" void site_025034B0(Cpu* c) { true60::ratio_end(c, 31); }
// camera: followCamera: direction V
extern "C" void site_025034D0(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x3C
extern "C" void site_02503540(Cpu* c) { true60::ratio_begin(c, 31); }
extern "C" void site_02503544(Cpu* c) { true60::ratio_end(c, 31); }
// camera: followCamera: direction V (second branch)
extern "C" void site_02503564(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera: direction U towards behind the player
extern "C" void site_025035BC(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x60
extern "C" void site_02503670(Cpu* c) { true60::ratio_begin(c, 31); }
extern "C" void site_02503674(Cpu* c) { true60::ratio_end(c, 31); }
// camera: followCamera state +0x1C
extern "C" void site_025037B0(Cpu* c) { true60::ratio_begin(c, 1); }
extern "C" void site_025037B4(Cpu* c) { true60::ratio_end(c, 1); }
// camera: followCamera state +0x40
extern "C" void site_02503E20(Cpu* c) { true60::ratio_begin(c, 10); }
extern "C" void site_02503E24(Cpu* c) { true60::ratio_end(c, 10); }
// camera: followCamera state +0x40
extern "C" void site_02503EC8(Cpu* c) { true60::ratio_begin(c, 7); }
extern "C" void site_02503ECC(Cpu* c) { true60::ratio_end(c, 7); }
// camera: followCamera: direction U, ratio m3B8 * cos V
extern "C" void site_025042F8(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera: direction U, ratio m3B8 * cos V (branch 2)
extern "C" void site_025043C8(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera: direction U, ratio m3B8 * cos V (branch 3)
extern "C" void site_0250447C(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x28
extern "C" void site_02504620(Cpu* c) { true60::ratio_begin(c, 8); }
extern "C" void site_02504624(Cpu* c) { true60::ratio_end(c, 8); }
// camera: followCamera state +0x68
extern "C" void site_02504660(Cpu* c) { true60::ratio_begin(c, 18); }
extern "C" void site_02504664(Cpu* c) { true60::ratio_end(c, 18); }
// camera: followCamera state +0x44
extern "C" void site_025046C0(Cpu* c) { true60::ratio_begin(c, 23); }
extern "C" void site_025046C4(Cpu* c) { true60::ratio_end(c, 23); }
// camera: followCamera state +0x28
extern "C" void site_025046FC(Cpu* c) { true60::ratio_begin(c, 12); }
extern "C" void site_02504700(Cpu* c) { true60::ratio_end(c, 12); }
// camera: followCamera state +0x68
extern "C" void site_025047B8(Cpu* c) { true60::ratio_begin(c, 0); }
extern "C" void site_025047BC(Cpu* c) { true60::ratio_end(c, 0); }
// camera: followCamera state +0x68
extern "C" void site_02504808(Cpu* c) { true60::ratio_begin(c, 29); }
extern "C" void site_0250480C(Cpu* c) { true60::ratio_end(c, 29); }
// camera: followCamera state +0x68
extern "C" void site_025049CC(Cpu* c) { true60::ratio_begin(c, 13); }
extern "C" void site_025049D0(Cpu* c) { true60::ratio_end(c, 13); }
// camera: followCamera: direction V, ratio from the follow work (+0x68)
extern "C" void site_02504B1C(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x20
extern "C" void site_02504B70(Cpu* c) { true60::ratio_begin(c, 23); }
extern "C" void site_02504B74(Cpu* c) { true60::ratio_end(c, 23); }
// camera: followCamera state +0x24
extern "C" void site_02504B78(Cpu* c) { true60::ratio_begin(c, 23); }
extern "C" void site_02504B7C(Cpu* c) { true60::ratio_end(c, 23); }
// camera: followCamera state +0x64
extern "C" void site_02504B94(Cpu* c) { true60::ratio_begin(c, 17); }
extern "C" void site_02504B98(Cpu* c) { true60::ratio_end(c, 17); }
// camera: followCamera state +0x3C
extern "C" void site_02504BA8(Cpu* c) { true60::ratio_begin(c, 0); }
extern "C" void site_02504BAC(Cpu* c) { true60::ratio_end(c, 0); }
// camera: followCamera state +0x64
extern "C" void site_02504C00(Cpu* c) { true60::ratio_begin(c, 17); }
extern "C" void site_02504C04(Cpu* c) { true60::ratio_end(c, 17); }
// camera: followCamera state +0x3C
extern "C" void site_02504C14(Cpu* c) { true60::ratio_begin(c, 0); }
extern "C" void site_02504C18(Cpu* c) { true60::ratio_end(c, 0); }
// camera: followCamera state +0x3C
extern "C" void site_02504C68(Cpu* c) { true60::ratio_begin(c, 19); }
extern "C" void site_02504C6C(Cpu* c) { true60::ratio_end(c, 19); }
// camera: followCamera: mEye += (m3CC - mEye) * 0.75
extern "C" void site_02504D50(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera state +0x70
extern "C" void site_02504DA0(Cpu* c) { true60::ratio_begin(c, 17); }
extern "C" void site_02504DA4(Cpu* c) { true60::ratio_end(c, 17); }
// camera: followCamera state +0x60
extern "C" void site_02504DB0(Cpu* c) { true60::ratio_begin(c, 8); }
extern "C" void site_02504DB4(Cpu* c) { true60::ratio_end(c, 8); }
// camera: followCamera: bank += (fan bank - bank) * ratio
extern "C" void site_02504ECC(Cpu* c) { true60::ratio_arg(c, 1); }
// camera: followCamera: bank (second branch)
extern "C" void site_02504F5C(Cpu* c) { true60::ratio_arg(c, 1); }
